ansible_user: admin
ansible_connection: network_cli
ansible_password: "{{ lookup('env', 'ansible_ssh_password' )}}"
ansible_become: True
ansible_become_method: enable
ansible_become_pass: "{{ ansible_password }}"

